# Generated by Django 4.2.2 on 2023-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_balance_id_alter_condition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cred_level',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='message',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
