# Generated by Django 4.2.2 on 2023-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_message_cred_level_alter_message_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='cred_level',
        ),
        migrations.AlterField(
            model_name='message',
            name='month',
            field=models.IntegerField(),
        ),
    ]
