# Generated by Django 4.2.2 on 2023-07-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetagging', '0002_groundtruthtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundtruthtag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagetask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
